// <auto-generated />
using MeuBanco.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace desafio_bem_promotora.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240418135351_RenameTableToRespostasPesquisas")]
    partial class RenameTableToRespostasPesquisas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntradaDeDados.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Convenio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaixaSalarial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoEmprestimo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MotivoEmprestimo");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("EntradaDeDados.Models.RespostasCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Convenio")
                        .HasColumnType("int");

                    b.Property<int>("FaixaIdade")
                        .HasColumnType("int");

                    b.Property<int>("FaixaSalarial")
                        .HasColumnType("int");

                    b.Property<int>("MotivoEmprestimo")
                        .HasColumnType("int")
                        .HasColumnName("MotivoEmprestimo");

                    b.HasKey("Id");

                    b.ToTable("RespostasClientes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
